In [1]:
import tensorflow as tf
import numpy as np
from glob import glob
import pickle
from random import shuffle

/home/rupak/anaconda3/envs/tfgpu/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
trData = glob("/home/rupak/Ariviyal/Dataset/cifar-10-batches-py/data*")
teData = glob("/home/rupak/Ariviyal/Dataset/cifar-10-batches-py/test_batch")
print(trData)
print(teData)

['/home/rupak/Ariviyal/Dataset/cifar-10-batches-py/data_batch_1', '/home/rupak/Ariviyal/Dataset/cifar-10-batches-py/data_batch_4', '/home/rupak/Ariviyal/Dataset/cifar-10-batches-py/data_batch_2', '/home/rupak/Ariviyal/Dataset/cifar-10-batches-py/data_batch_3', '/home/rupak/Ariviyal/Dataset/cifar-10-batches-py/data_batch_5']
['/home/rupak/Ariviyal/Dataset/cifar-10-batches-py/test_batch']


In [3]:
def unpickle(file):
    with open(file, 'rb') as fo:
        dict = pickle.load(fo, encoding='bytes')
    return dict

In [52]:
xtr = []
ytr = []
xte = []
yte = []
xtr = np.concatenate( [unpickle(i)[b'data'] for i in trData] )
ytr = np.concatenate( [np.asarray(unpickle(i)[b'labels']) for i in trData] )
xte = unpickle(teData[0])[b'data']
yte = np.asarray( unpickle(teData[0])[b'labels'] )
ypr = np.zeros(10000)

In [46]:
# s = list(zip(xtr,ytr))
# shuffle(s)
# xtr,ytr = zip(*s)
# t = list(zip(xte,yte))
# shuffle(t)
# xte,yte = zip(*t)
# xtr = np.asarray(list(xtr[:5000]))
# ytr = np.asarray(list(ytr[:5000]))
# xte = np.asarray(list(xte[:500]))
# yte = np.asarray(list(yte[:500]))

In [6]:
print(np.shape(xtr))
print(np.shape(ytr))
print(np.shape(xte))
print(np.shape(yte))

print(xtr[1:5])
print(ytr[1:5])

(50000, 3072)
(50000,)
(10000, 3072)
(10000,)
[[154 126 105 ... 139 142 144]
 [255 253 253 ...  83  83  84]
 [ 28  37  38 ...  28  37  46]
 [170 168 177 ...  82  78  80]]
[9 9 4 1]


In [7]:
#txtr = tf.convert_to_tensor(xtr, dtype=tf.float32)
#tytr = tf.convert_to_tensor(ytr, dtype=tf.float32)
#txte = tf.convert_to_tensor(xte, dtype=tf.float32)
#tyte = tf.convert_to_tensor(yte, dtype=tf.float32)
txtr = tf.placeholder(tf.float32, [None, 3072])
txte = tf.placeholder(tf.float32, [3072])

In [8]:
dist = tf.reduce_sum( tf.abs(tf.subtract(txtr,txte)), 1 )
pred = tf.argmin(dist)
accuracy = 0

In [9]:
%%time
init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    for i in range(np.shape(xte)[0]):
        index = sess.run(pred, feed_dict = { txtr : xtr, txte : xte[i,:]})
        ypr[i] = ytr[index]
        if i%100 == 0:
            print(i)
        
accuracy = (np.sum(np.asarray(ypr) == yte))/(np.shape(xte)[0])
print(accuracy)

0
50
100
150
200
250
300
350
400
450
500
550
600
650
700
750
800
850
900
950
1000
1050
1100
1150
1200
1250
1300
1350
1400
1450
1500
1550
1600
1650
1700
1750
1800
1850
1900
1950
2000
2050
2100
2150
2200
2250
2300
2350
2400
2450
2500
2550
2600
2650
2700
2750
2800
2850
2900
2950
3000
3050
3100
3150
3200
3250
3300
3350
3400
3450
3500
3550
3600
3650
3700
3750
3800
3850
3900
3950
4000
4050
4100
4150
4200
4250
4300
4350
4400
4450
4500
4550
4600
4650
4700
4750
4800
4850
4900
4950
5000
5050
5100
5150
5200
5250
5300
5350
5400
5450
5500
5550
5600
5650
5700
5750
5800
5850
5900
5950
6000
6050
6100
6150
6200
6250
6300
6350
6400
6450
6500
6550
6600
6650
6700
6750
6800
6850
6900
6950
7000
7050
7100
7150
7200
7250
7300
7350
7400
7450
7500
7550
7600
7650
7700
7750
7800
7850
7900
7950
8000
8050
8100
8150
8200
8250
8300
8350
8400
8450
8500
8550
8600
8650
8700
8750
8800
8850
8900
8950
9000
9050
9100
9150
9200
9250
9300
9350
9400
9450
9500
9550
9600
9650
9700
9750
9800
9850
9900
9950
0.0
CPU times: user 48m

/home/rupak/anaconda3/envs/tfgpu/lib/python3.5/site-packages/ipykernel_launcher.py:10: DeprecationWarning: elementwise == comparison failed; this will raise an error in the future.
  # Remove the CWD from sys.path while we load stuff.
